version: '3'
services:
  backend:
    image: python:3.9
    container_name: backend
    volumes:
      - ./backend:/app
    working_dir: /app
    command: python app.py
    ports:
      - "5000:5000"

  frontend:
    image: node:14
    container_name: frontend
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"
      
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"
